### ISSUE TITLE
traceback on too-long serial

### ISSUE THREAD

**Issue by YesThatAllen** [watchmanmonitoring/MacModelShelf#1]
When testing a serial that is too long, but has no S, we get this error:

`./macmodelshelf.py W89390DYYBZRA`

results in 

```
Traceback (most recent call last):
  File "/Users/Shared/Development/MacModelShelf/macmodelshelf.py", line 64, in <module>
    m = model(model_code(sys.argv[1]))
  File "/Users/Shared/Development/MacModelShelf/macmodelshelf.py", line 40, in model
    code = code.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

If there isn't an S to strip, change the output to the standard:
`Unknown model 'W89390DYYBZRAA'`

**Comment by garybourgeois** [comment]
I'm not really sure the "right" way to fix this, like if there should be support added in the `model_code()` block or how that should be done if so.  So what I've done for now at least is return `None` from the `model()` function of the provided `code` is `None`.  This will print the `Unknown model` statement by failing the `if m` check.

**Comment by garybourgeois** [comment]
Forgot to reference the issue in the commit:  3a9f0ac8323ecc195280328058a0bf1f2750fcb6

**Comment by YesThatAllen** [comment]
Fixed in https://github.com/MagerValp/MacModelShelf/pull/19
