### ISSUE TITLE
sort 3 digit, then 4

### ISSUE THREAD

**Issue by YesThatAllen** [watchmanmonitoring/MacModelShelf#3]
Add a flag to sort by 3 digit then 4 digit snippets, keeping all newer models next to each other.

**Comment by YesThatAllen** [comment]
Adding this in the `snippet-sorting` branch would be great

**Comment by garybourgeois** [comment]
Should this really be a flag, or just how it's done?  Is there any reason to _not_ sort this way?

**Comment by YesThatAllen** [comment]
Sorting this with 3, then 4 can be the new default.  A flag could be added to go back to the old way if needed.

**Comment by YesThatAllen** [comment]
This is working for me.
